# Generated by Django 3.2.5 on 2022-09-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='actors',
            new_name='Actors',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='awards',
            new_name='Awards',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='boxOffice',
            new_name='BoxOffice',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='director',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='genre',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='language',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='metascore',
            new_name='Metascore',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='plot',
            new_name='Plot',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='poster',
            new_name='Poster',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='production',
            new_name='Production',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='rated',
            new_name='Rated',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='ratings',
            new_name='Ratings',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='released',
            new_name='Released',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='response',
            new_name='Response',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='runtime',
            new_name='Runtime',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='website',
            new_name='Website',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='writer',
            new_name='Writer',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='year',
            new_name='Year',
        ),
    ]
